-- Add pinning and sort order support
ALTER TABLE notes ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE notes ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0 NOT NULL;

ALTER TABLE lists ADD COLUMN IF NOT EXISTS is_pinned BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE lists ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0 NOT NULL;
